#!/usr/bin/env bash

set -e

LIB="$1"

test -n "$LIB"

SRC=src/$LIB
DEST=dist/$LIB

test -e $SRC/README.md
rm -Rf dist
ttsc

find dist -mindepth 1 -maxdepth 1 -not -name "$LIB" -exec rm -R {} \;

find "$SRC" -mindepth 1 -maxdepth 1 -not -name '*.ts' -not -name 'node_modules' -exec cp -t "$DEST" {} \;

echo "Test build"

rm -Rf /tmp/test-build
mkdir -p /tmp/test-build

cp -R $DEST /tmp/test-build

cd /tmp/test-build/$LIB

npm i
node .

echo "Done"