#!/usr/bin/env bash

set -e

LIB="$1"

test -n "$LIB"

SRC=src/$LIB
DEST=dist/$LIB

./test "$LIB"
./build "$LIB"

read -p 'major/minor/patch ? ' NPM_VERSION_ARG

cd $SRC

npm version $NPM_VERSION_ARG

VERSION=$(node -e 'process.stdout.write(require("./package.json").version)')

cd -

git add -p
git commit -m "$LIB/$VERSION"
git tag -a "$LIB/$VERSION" -m "$LIB/$VERSION"

./build "$LIB"

cd $DEST

npm login
trap "npm logout" EXIT

npm publish --access public

#git push