#!/usr/bin/env bash

set -e

LIBS=$*
test -n "$LIBS"

for LIB in $LIBS; do
    echo ">>>>>>>> $LIB"
    ./test "$LIB"
    ./build "$LIB"
done

INIT_PWD="$(pwd)"

npm login
trap "npm logout" EXIT

for LIB in $LIBS; do
    echo ">>>>>>>> $LIB"

    cd "$INIT_PWD"

    SRC=src/$LIB
    DEST=dist/$LIB

    read -p 'major/minor/patch ? ' NPM_VERSION_ARG

    cd $SRC

    npm version $NPM_VERSION_ARG

    VERSION=$(node -e 'process.stdout.write(require("./package.json").version)')

    cd -

    git add -p
    read -p 'Commit message ? ' COMMIT_MSG
    git commit -m "$LIB/$VERSION $COMMIT_MSG"
    git tag -a "$LIB/$VERSION" -m "$LIB/$VERSION"

    ./build "$LIB"

    cd $DEST

    npm publish --access public

    cd -

    #git push

done






